name: install-examples

inputs:
  python-version:
    description: Python version
    required: false
    default: '3.11'
    type: string

runs:
  using: composite
  steps:
    - name: Install Melting Pot
      id: install-meltingpot
      uses: ./.github/actions/install-meltingpot
      with:
        python-version: ${{ inputs.python-version }}

    - name: Restore Examples installation
      id: restore
      uses: actions/cache/restore@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        path: venv
        key: install-examples-${{ steps.install-meltingpot.outputs.key }}-${{ hashFiles('examples/requirements.txt') }}

    - name: Activate venv
      shell: bash
      run: |
        echo "${PWD}/venv/bin" >> $GITHUB_PATH

    - name: Install requirements for examples
      if: steps.restore.outputs.cache-hit != 'true'
      shell: bash
      run: |
        pip install -r examples/requirements.txt

    - name: Show installation
      shell: bash
      run: |
        which python
        python --version
        which pip
        pip --version
        which pylint
        pylint --version
        which pytest
        pytest --version
        which pytype
        pytype --version
        pip list

    - name: Save Examples installation
      if: steps.restore.outputs.cache-hit != 'true'
      uses: actions/cache/save@0c45773b623bea8c8e75f6c82b208c3cf94ea4f9
      with:
        path: venv
        key: ${{ steps.restore.outputs.cache-primary-key }}
